In [1]:
import itertools as it
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import pandas as pd

In [114]:
Crime = pd.read_csv('state_crime.csv', usecols = range(0,12))
Crime

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,Data.Rates.Violent.Rape,Data.Rates.Violent.Robbery
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,8.6,27.5
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,7.6,19.1
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,6.5,22.5
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,5.7,24.7
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,11.7,29.1
...,...,...,...,...,...,...,...,...,...,...,...,...
3110,Wyoming,2015,586107,1902.6,300.6,1500.9,101.0,222.1,179.8,2.7,29.5,10.1
3111,Wyoming,2016,585501,1957.3,302.5,1518.2,136.6,244.2,195.7,3.4,35.0,10.1
3112,Wyoming,2017,579315,1830.4,275.0,1421.0,134.5,237.5,176.4,2.6,45.4,13.1
3113,Wyoming,2018,577737,1785.1,264.0,1375.9,145.2,212.2,150.6,2.3,42.1,17.3
3114,Wyoming,2019,578759,1571.1,241.2,1206.7,123.2,217.4,147.6,2.2,56.0,11.6

In [115]:
Crime['Total Crime Rate'] = Crime['Data.Rates.Property.All'] + Crime['Data.Rates.Violent.All']

In [116]:
Crime

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,Data.Rates.Violent.Rape,Data.Rates.Violent.Robbery,Total Crime Rate
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,8.6,27.5,1222.0
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,7.6,19.1,1154.0
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,6.5,22.5,1224.3
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,5.7,24.7,1333.6
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,11.7,29.1,1571.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3110,Wyoming,2015,586107,1902.6,300.6,1500.9,101.0,222.1,179.8,2.7,29.5,10.1,2124.7
3111,Wyoming,2016,585501,1957.3,302.5,1518.2,136.6,244.2,195.7,3.4,35.0,10.1,2201.5
3112,Wyoming,2017,579315,1830.4,275.0,1421.0,134.5,237.5,176.4,2.6,45.4,13.1,2067.9
3113,Wyoming,2018,577737,1785.1,264.0,1375.9,145.2,212.2,150.6,2.3,42.1,17.3,1997.3
3114,Wyoming,2019,578759,1571.1,241.2,1206.7,123.2,217.4,147.6,2.2,56.0,11.6,1788.5

In [117]:
Crime_Modern = Crime[['State','Year','Total Crime Rate']][(Crime['State']=='Florida') & (Crime['Year'] >= 1980) | (Crime['State']=='New York') & (Crime['Year'] >= 1980) | (Crime['State']=='Texas') & (Crime['Year'] >= 1980) | (Crime['State']=='Illinois') & (Crime['Year'] >= 1980) | (Crime['State']=='California') & (Crime['Year'] >= 1980) ]
Crime_Modern.head(50)

          State  Year  Total Crime Rate
260  California  1980            7833.1
261  California  1981            7590.5
262  California  1982            7285.4
263  California  1983            6677.5
264  California  1984            6468.4
265  California  1985            6518.0
266  California  1986            6762.8
267  California  1987            6506.4
268  California  1988            6635.5
269  California  1989            6763.5
270  California  1990            6603.6
271  California  1991            6772.6
272  California  1992            6679.5
273  California  1993            6456.9
274  California  1994            6173.8
275  California  1995            5831.1
276  California  1996            5207.8
277  California  1997            4865.4
278  California  1998            4342.8
279  California  1999            3805.0
280  California  2000            3739.8
281  California  2001            3893.2
282  California  2002            3956.6
283  California  2003            4006.0
284  California  2004            3951.7
285  California  2005            3847.0
286  California  2006            3715.2
287  California  2007            3567.6
288  California  2008            3445.2
289  California  2009            3204.3
290  California  2010            3069.5
291  California  2011            2995.4
292  California  2012            3181.8
293  California  2013            3060.2
294  California  2014            2837.2
295  California  2015            3044.6
296  California  2016            2998.3
297  California  2017            2946.0
298  California  2018            2827.8
299  California  2019            2772.4
560     Florida  1980            8401.9
561     Florida  1981            8032.5
562     Florida  1982            7465.2
563     Florida  1983            6781.1
564     Florida  1984            6821.3
565     Florida  1985            7574.2
566     Florida  1986            8228.4
567     Florida  1987            8503.1
568     Florida  1988            8937.6
569     Florida  1989            8804.5

In [ ]:
Crime_Modern = Crime[['State','Year','Total Crime Rate']][(Crime['State']=='') & (Crime['Year'] >= 1980)